<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="wwwroot\images\avatar\" />
    <Folder Include="wwwroot\images\uploaded\cover\" />
    <Folder Include="wwwroot\images\uploaded\profile\" />
    <Folder Include="wwwroot\post\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\tailwind.css" />
    <None Include="wwwroot\js\script.js" />
    <None Include="wwwroot\js\simplebar.js" />
    <None Include="wwwroot\js\uikit.min.js" />
    <None Include="wwwroot\syntax-highlighter\scripts\shBrushJScript.js" />
    <None Include="wwwroot\syntax-highlighter\scripts\shBrushXml.js" />
    <None Include="wwwroot\syntax-highlighter\scripts\shCore.js" />
    <None Include="wwwroot\syntax-highlighter\styles\shCore.css" />
    <None Include="wwwroot\syntax-highlighter\styles\shCoreMidnight.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
